# Prepare and render a significance report
#
# This script generates a significance-type report based on an enriched
# `CALANGO`-type list output by `run_CALANGO()`.
#
# @param defs an enriched `CALANGO`-type list generated by `run_CALANGO()`
# @param ... other parameters (unused for standalone calls, used internally
# by other functions in the package)
#

make_significance_report <- function(defs, ...){

  stop("Type 'significance' not yet available.")
}
